add new OpenDUT
CSA-FEDERATE/Proposed-BuildingBlocks pull request #23
Opened 2024-09-10 07:44 UTC by madri2

2024-10-03 09:06 UTC, LS0205 requested changes
please rework it as suggested by the comments

2024-10-03 09:06 UTC, LS0205 commented on BB-EST/Testing/BB_OpenDUT.md
> +- EST, CEST, SC-TC, CSC-TC
Bitte Tags auf - BB-EST, BB-CEST, BB-SC-TC, BB-CSC-TC ändern

2024-10-03 09:06 UTC, LS0205 commented on BB-EST/Testing/BB_OpenDUT.md
> +- Middleware
Auf "MWLayer" ändern

2024-10-03 17:04 UTC, madri2 commented on BB-EST/Testing/BB_OpenDUT.md
> +- EST, CEST, SC-TC, CSC-TC
done

2024-10-03 17:04 UTC, madri2 commented on BB-EST/Testing/BB_OpenDUT.md
> +- Middleware
Done

2024-10-04 12:08 UTC, LS0205 approved these changes
ok

2024-10-04 12:56 UTC, merged